var annotated_dup =
[
    [ "Spelunx", "d1/d34/namespaceSpelunx.html", [
      [ "Fullscreen", "d9/de8/namespaceSpelunx_1_1Fullscreen.html", [
        [ "AutoActivateFullscreenPreview", "d3/d7f/classSpelunx_1_1Fullscreen_1_1AutoActivateFullscreenPreview.html", "d3/d7f/classSpelunx_1_1Fullscreen_1_1AutoActivateFullscreenPreview" ],
        [ "ToggleFullscreenGameView", "dc/d95/classSpelunx_1_1Fullscreen_1_1ToggleFullscreenGameView.html", "dc/d95/classSpelunx_1_1Fullscreen_1_1ToggleFullscreenGameView" ]
      ] ],
      [ "Orbbec", "d4/d22/namespaceSpelunx_1_1Orbbec.html", [
        [ "BodyData", "d2/dda/structSpelunx_1_1Orbbec_1_1BodyData.html", "d2/dda/structSpelunx_1_1Orbbec_1_1BodyData" ],
        [ "BodyTracker", "d2/d27/classSpelunx_1_1Orbbec_1_1BodyTracker.html", "d2/d27/classSpelunx_1_1Orbbec_1_1BodyTracker" ],
        [ "BodyTrackerAvatar", "dc/d9e/classSpelunx_1_1Orbbec_1_1BodyTrackerAvatar.html", "dc/d9e/classSpelunx_1_1Orbbec_1_1BodyTrackerAvatar" ],
        [ "BodyTrackerInspector", "df/d42/classSpelunx_1_1Orbbec_1_1BodyTrackerInspector.html", "df/d42/classSpelunx_1_1Orbbec_1_1BodyTrackerInspector" ],
        [ "BodyTrackerManager", "da/dca/classSpelunx_1_1Orbbec_1_1BodyTrackerManager.html", "da/dca/classSpelunx_1_1Orbbec_1_1BodyTrackerManager" ],
        [ "BodyTrackerManagerInspector", "de/de3/classSpelunx_1_1Orbbec_1_1BodyTrackerManagerInspector.html", "de/de3/classSpelunx_1_1Orbbec_1_1BodyTrackerManagerInspector" ],
        [ "FrameData", "d6/d02/classSpelunx_1_1Orbbec_1_1FrameData.html", "d6/d02/classSpelunx_1_1Orbbec_1_1FrameData" ],
        [ "FrameDataProvider", "d6/dad/classSpelunx_1_1Orbbec_1_1FrameDataProvider.html", "d6/dad/classSpelunx_1_1Orbbec_1_1FrameDataProvider" ]
      ] ],
      [ "Vive", "d9/ddb/namespaceSpelunx_1_1Vive.html", [
        [ "CavernInteraction", "d3/d86/classSpelunx_1_1Vive_1_1CavernInteraction.html", "d3/d86/classSpelunx_1_1Vive_1_1CavernInteraction" ],
        [ "EvadeInteraction", "d7/d67/classSpelunx_1_1Vive_1_1EvadeInteraction.html", "d7/d67/classSpelunx_1_1Vive_1_1EvadeInteraction" ],
        [ "FollowInteraction", "da/df9/classSpelunx_1_1Vive_1_1FollowInteraction.html", "da/df9/classSpelunx_1_1Vive_1_1FollowInteraction" ],
        [ "FollowMotion", "d7/da5/classSpelunx_1_1Vive_1_1FollowMotion.html", "d7/da5/classSpelunx_1_1Vive_1_1FollowMotion" ],
        [ "Interaction", "df/dd7/classSpelunx_1_1Vive_1_1Interaction.html", "df/dd7/classSpelunx_1_1Vive_1_1Interaction" ],
        [ "LookAt", "d7/df6/classSpelunx_1_1Vive_1_1LookAt.html", null ],
        [ "OrbitCavernInteraction", "da/d7d/classSpelunx_1_1Vive_1_1OrbitCavernInteraction.html", "da/d7d/classSpelunx_1_1Vive_1_1OrbitCavernInteraction" ],
        [ "OVRT_BoundTrackedObject", "d4/d6d/classSpelunx_1_1Vive_1_1OVRT__BoundTrackedObject.html", "d4/d6d/classSpelunx_1_1Vive_1_1OVRT__BoundTrackedObject" ],
        [ "OVRT_Events", "d8/d96/classSpelunx_1_1Vive_1_1OVRT__Events.html", "d8/d96/classSpelunx_1_1Vive_1_1OVRT__Events" ],
        [ "OVRT_RenderModel", "d6/d9b/classSpelunx_1_1Vive_1_1OVRT__RenderModel.html", "d6/d9b/classSpelunx_1_1Vive_1_1OVRT__RenderModel" ],
        [ "OVRT_TrackedDevice", "df/d93/classSpelunx_1_1Vive_1_1OVRT__TrackedDevice.html", "df/d93/classSpelunx_1_1Vive_1_1OVRT__TrackedDevice" ],
        [ "OVRT_TrackedObject", "db/d50/classSpelunx_1_1Vive_1_1OVRT__TrackedObject.html", "db/d50/classSpelunx_1_1Vive_1_1OVRT__TrackedObject" ],
        [ "OVRT_Utils", "d7/d48/classSpelunx_1_1Vive_1_1OVRT__Utils.html", "d7/d48/classSpelunx_1_1Vive_1_1OVRT__Utils" ],
        [ "TrackerData", "da/d92/classSpelunx_1_1Vive_1_1TrackerData.html", "da/d92/classSpelunx_1_1Vive_1_1TrackerData" ],
        [ "UpdateVsyncTimestamp", "dc/d8a/classSpelunx_1_1Vive_1_1UpdateVsyncTimestamp.html", null ],
        [ "Vive_Manager", "d8/d2a/classSpelunx_1_1Vive_1_1Vive__Manager.html", "d8/d2a/classSpelunx_1_1Vive_1_1Vive__Manager" ],
        [ "ViveController", "d7/df0/classSpelunx_1_1Vive_1_1ViveController.html", "d7/df0/classSpelunx_1_1Vive_1_1ViveController" ],
        [ "ViveDebugKeys", "de/d71/classSpelunx_1_1Vive_1_1ViveDebugKeys.html", "de/d71/classSpelunx_1_1Vive_1_1ViveDebugKeys" ],
        [ "ViveDebugRenderer", "d0/dfb/classSpelunx_1_1Vive_1_1ViveDebugRenderer.html", null ],
        [ "ViveTracker", "df/d90/classSpelunx_1_1Vive_1_1ViveTracker.html", "df/d90/classSpelunx_1_1Vive_1_1ViveTracker" ],
        [ "Zones", "d4/d24/classSpelunx_1_1Vive_1_1Zones.html", "d4/d24/classSpelunx_1_1Vive_1_1Zones" ]
      ] ],
      [ "CavernDebugKeys", "d3/d24/classSpelunx_1_1CavernDebugKeys.html", "d3/d24/classSpelunx_1_1CavernDebugKeys" ],
      [ "CavernRenderer", "db/d6f/classSpelunx_1_1CavernRenderer.html", "db/d6f/classSpelunx_1_1CavernRenderer" ],
      [ "CavernRenderPass", "d3/d01/classSpelunx_1_1CavernRenderPass.html", "d3/d01/classSpelunx_1_1CavernRenderPass" ],
      [ "CavernToolsPanel", "d4/d7a/classSpelunx_1_1CavernToolsPanel.html", "d4/d7a/classSpelunx_1_1CavernToolsPanel" ],
      [ "DirectCanvasRenderPass", "da/da0/classSpelunx_1_1DirectCanvasRenderPass.html", "da/da0/classSpelunx_1_1DirectCanvasRenderPass" ],
      [ "IDebugKeys", "d1/df7/interfaceSpelunx_1_1IDebugKeys.html", "d1/df7/interfaceSpelunx_1_1IDebugKeys" ],
      [ "MathsUtil", "da/d53/classSpelunx_1_1MathsUtil.html", "da/d53/classSpelunx_1_1MathsUtil" ],
      [ "OrbbecToolsPanel", "d2/de4/classSpelunx_1_1OrbbecToolsPanel.html", "d2/de4/classSpelunx_1_1OrbbecToolsPanel" ],
      [ "ScreenSpaceCanvasRenderer", "d7/dba/classSpelunx_1_1ScreenSpaceCanvasRenderer.html", null ],
      [ "TagUtil", "d5/d33/classSpelunx_1_1TagUtil.html", "d5/d33/classSpelunx_1_1TagUtil" ],
      [ "ViveToolsPanel", "d7/d07/classSpelunx_1_1ViveToolsPanel.html", "d7/d07/classSpelunx_1_1ViveToolsPanel" ],
      [ "WorldSpaceMeshCanvas", "d8/d78/classSpelunx_1_1WorldSpaceMeshCanvas.html", "d8/d78/classSpelunx_1_1WorldSpaceMeshCanvas" ]
    ] ],
    [ "AudioManager", "db/d48/classAudioManager.html", "db/d48/classAudioManager" ],
    [ "BuoyantObject", "d6/d37/classBuoyantObject.html", "d6/d37/classBuoyantObject" ],
    [ "CircularMovement", "dc/d26/classCircularMovement.html", null ],
    [ "CreatureBehavior", "d4/d5c/classCreatureBehavior.html", "d4/d5c/classCreatureBehavior" ],
    [ "FiniteStateMachine", "d7/d63/classFiniteStateMachine.html", "d7/d63/classFiniteStateMachine" ],
    [ "GameManager", "d2/d2c/classGameManager.html", "d2/d2c/classGameManager" ],
    [ "GerstnerWaveDisplacement", "dc/d5c/classGerstnerWaveDisplacement.html", "dc/d5c/classGerstnerWaveDisplacement" ],
    [ "HuggingState", "db/d20/classHuggingState.html", "db/d20/classHuggingState" ],
    [ "MirroringState", "d6/dfb/classMirroringState.html", "d6/dfb/classMirroringState" ],
    [ "OnGroundState", "d3/df8/classOnGroundState.html", "d3/df8/classOnGroundState" ],
    [ "SampleDebugKeys", "d3/daf/classSampleDebugKeys.html", "d3/daf/classSampleDebugKeys" ],
    [ "SoundController", "d0/d36/classSoundController.html", "d0/d36/classSoundController" ],
    [ "StartState", "d9/d1e/classStartState.html", "d9/d1e/classStartState" ],
    [ "State", "d7/d97/classState.html", "d7/d97/classState" ],
    [ "TrackerData", "dd/d17/classTrackerData.html", "dd/d17/classTrackerData" ],
    [ "TrackingArea", "da/d34/classTrackingArea.html", "da/d34/classTrackingArea" ]
];